workspace(name = "fmeum_rules_jni_tests")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_jar")

local_repository(
    name = "fmeum_rules_jni",
    path = "../",
)

load("@fmeum_rules_jni//jni:repositories.bzl", "rules_jni_dependencies")

rules_jni_dependencies()

http_jar(
    name = "junit",
    sha256 = "8e495b634469d64fb8acfa3495a065cbacc8a0fff55ce1e31007be4c16dc57d3",
    urls = [
        "https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar",
    ],
)

register_toolchains(
    "@bazel_skylib//toolchains/unittest:cmd_toolchain",
    "@bazel_skylib//toolchains/unittest:bash_toolchain",
)
