name: Build all targets and run all tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:

  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        bazel: ["4.2.1", "rolling"]
        os: [ubuntu-latest, macos-latest, windows-latest]
        jdk: [8, 11, 17]
        include:
          - os: ubuntu-latest
            cache: "/home/runner/.cache/bazel-disk"
          - os: macos-latest
            cache: "/private/var/tmp/bazel-disk"
          - os: windows-latest
            cache: "C:\\tmp\\bazel-disk"
    env:
      BAZELISK_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      - name: Mount Bazel disk cache
        uses: actions/cache@v2
        with:
          path: ${{ matrix.cache }}
          key: bazel-disk-cache-${{ matrix.bazel }}-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Build
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel }}
        run: bazelisk build --config=ci --disk_cache=${{ matrix.cache }} //...

      - name: Test
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel }}
        run: bazelisk test --config=ci --disk_cache=${{ matrix.cache }} //...

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: testlogs-${{ matrix.bazel}}-${{ matrix.os }}-${{ matrix.jdk }}
          # https://github.com/actions/upload-artifact/issues/92#issuecomment-711107236
          path: bazel-testlogs*/**/test.log
